# .github/workflows/cogserver.yml

name: CogServer Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test CogServer
    runs-on: ubuntu-latest
    needs: [atomspace]
    container:
      image: opencog/opencog-deps
      options: --user root
    env:
      CCACHE_DIR: /ws/ccache
      MAKEFLAGS: -j2
    steps:
      - name: Checkout CogServer Repository
        uses: actions/checkout@v4

      - name: Set up Ccache
        uses: actions/cache@v4
        with:
          path: /ws/ccache
          key: ccache-cogserver-${{ runner.os }}-${{ hashFiles('**/*.cpp', '**/*.h') }}
          restore-keys: |
            ccache-cogserver-${{ runner.os }}-
            ccache-cogserver-

      - name: Create Build Directory
        run: mkdir -p build

      - name: Configure Build
        run: |
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          make

      - name: Build Tests
        run: |
          cd build
          make tests

      - name: Run Tests
        run: |
          cd build
          make check ARGS="$MAKEFLAGS"

      - name: Upload CogServer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cogserver
          path: build/
