name: Sync Repositories

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  fetch:
    needs: setup
    uses: ./.github/workflows/fetch.yml

  read:
    needs: fetch
    uses: ./.github/workflows/read.yml

  sync:
    needs: fetch
    uses: ./.github/workflows/sync.yml
    with:
      org_name: opencog

  clean:
    needs: sync
    uses: ./.github/workflows/clean.yml
